# $FreeBSD$

PORTNAME=	mm8dread
PORTVERSION=	0.4
CATEGORIES=	misc
MASTER_SITES=	http://www.pozsarzs.hu/packages/software/mm8dread

MAINTAINER=	pozsarzs@gmail.com
COMMENT=	Status reader program for MM8D device

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)

