#!/bin/bash
# +----------------------------------------------------------------------------+
# | MM8DRead v0.4 * Status reader program for MM8D device                      |
# | Copyright (C) 2020-2023 Pozsár Zsolt <pozsarzs@gmail.com>                  |
# | remove_links                                                               |
# | Symbolic link remover script                                               |
# +----------------------------------------------------------------------------+

# constants
SWN="MM8DRead"
SWV=`cat documents/VERSION`
CR=`cat documents/copyright`
INSTDIR=/opt/mm8dread
LINKDIR=/usr/local
BINFILES="mm8dread"

# link remover
clear
echo "--------------------------------------------------------------------------------"
echo "$SWN $SWV symbolic link remover script"
echo "$CR"
echo "--------------------------------------------------------------------------------"
if [ `whoami` != 'root' ]
then echo 'ERROR: You are not root!'; exit
fi
sleep 1
echo "Removing symbolic links..."
for f in $BINFILES
do
  rm --force $LINKDIR/bin/$f 2> /dev/null
  echo "  $LINKDIR/bin/$f"
  if [ -f $LINKDIR/bin/$f.desktop ];
  then
    rm --force $LINKDIR/share/applications/$f.desktop 2> /dev/null
    echo "  $LINKDIR/share/applications/$f.desktop"
  fi
  if [ -f $f.xpm ];
  then
    rm --force $LINKDIR/share/pixmaps/$f.xpm 2> /dev/null
    echo "  $LINKDIR/share/pixmaps/$f.xpm"
  fi
  rm --force $LINKDIR/share/man/man1/$f.1 2> /dev/null
  echo "  $LINKDIR/share/man/man1/$f.1"
done
echo "Done."
